# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b4ccdfc4617da3f71f6fd6b6c8c10175057ef56c29d75e19a72f01836ada600fd8056adfb7068e797d54dbd410b813d3ae5cf30c20a09dfc8900f71d727027c0


test:
  secret_key_base: 96588316ffc5e16a10d368a09d17df7c5ba6c333a431e47eb8e13bc53dd7904d3b8d6d027d47d6d53ef1bdd6185117d58d14c78862b517258826265920228730

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
